Repository blackberggroup/VA-OHIL, pull requests merged in 2024-02, with the labels that each got.

#16 font path fix, banner open/close fix
  _site/assets-3-5/css/_styles.css
  _site/assets-3-5/css/styles.css
  _site/assets/css/styles.css
  _site/assets/sass/_uswds-theme.scss
  _site/assets/sass/vha/components/navigation/_index.scss
  _site/assets/sass/vha/pages/home/divisions/_index.scss
  assets/css/styles.css
  assets/sass/_uswds-theme.scss
  assets/sass/vha/components/navigation/_index.scss
  assets/sass/vha/pages/home/divisions/_index.scss
Labels: bug

#17 Feature: 5961020831 - Infrastructure - OHIL
  .github/workflows/azure-static-web-apps-agreeable-meadow-016c48410.yml
  .github/workflows/changed-files.yml
  .github/workflows/compress.yml
  .github/workflows/deploy-dev-sandbox.yml
  .github/workflows/deploy-sandbox.yml
  .gitignore
Labels: image compression, ready for review

#18 added menu dropdown arrow bug fix
  .eleventyignore
  _includes/home/state-of-innovation.html
  _site/assets-3-5/css/styles.css
  _site/index.html
Labels: bug, ready for review

#21 correct deploy path
  .github/workflows/deploy-dev-sandbox.yml
  .github/workflows/deploy-sandbox.yml
  _includes/footer-sub.html
  _includes/header-sub.html
  _includes/iex-2023/about.html
  _includes/iex-2023/hero.html
  _includes/iex-2023/iex-talks.html
  _includes/iex-2023/keynote-speakers.html
  _site/assets/css/styles.css
  _site/coming-soon/index.html
  _site/views/iex-2023/index.html
  assets/css/styles.css
  views/iex-2023/index.html
Labels: bug, ready for review
